# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 331afb5207f709a6c07c0b02d515a0eb29426f000ed0b13db3bfe5df1da6971fcce2debcc5c6ad66465bfb4d87214f7a9dbf151fadee229223c3ca10cd1e3088

test:
  secret_key_base: 4085f8384714358ee60fafd2dcd10bb5c7c2defa8ae082a6456e57ebf930d4949f619f830790c6c760aecf4492f889ec46f621e402826f6ec3952dd8915e741f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
